"use client";

import Link from "next/link";
import { useQuery } from "@tanstack/react-query";
import { useState } from "react";

type User = { id: string; fullName: string | null; email: string; goal: string | null; createdAt: string; suspended: boolean; dailyCalorieTarget: number | null };
async function getUsers(query: string): Promise<User[]> { const response = await fetch(`/api/admin/users?q=${encodeURIComponent(query)}`); const payload = await response.json() as { users?: User[]; error?: string }; if (!response.ok) throw new Error(payload.error ?? "بارگذاری کاربران انجام نشد."); return payload.users ?? []; }
export function AdminUsers() { const [query, setQuery] = useState(""); const { data, error, isLoading } = useQuery({ queryKey: ["admin-users", query], queryFn: () => getUsers(query) }); return <section><h1 className="text-2xl font-bold">کاربران</h1><input className="mt-5 h-10 w-full max-w-md rounded-md border border-zinc-300 px-3 text-sm outline-none focus:ring-2 focus:ring-zinc-900" placeholder="جست‌وجوی نام یا ایمیل" value={query} onChange={(event) => setQuery(event.target.value)} />{error && <p className="mt-4 text-sm text-red-700">{error.message}</p>}<div className="mt-4 overflow-x-auto rounded-lg border border-zinc-200 bg-white"><table className="w-full min-w-[720px] text-right text-sm"><thead className="bg-zinc-50 text-xs text-zinc-500"><tr><th className="p-3">کاربر</th><th className="p-3">هدف</th><th className="p-3">هدف کالری</th><th className="p-3">ثبت‌نام</th><th className="p-3">وضعیت</th></tr></thead><tbody>{isLoading ? <tr><td className="p-4" colSpan={5}>در حال بارگذاری…</td></tr> : data?.map((user) => <tr className="border-t border-zinc-100 hover:bg-zinc-50" key={user.id}><td className="p-3"><Link className="font-medium hover:underline" href={`/admin/users/${user.id}`}>{user.fullName || "بدون نام"}</Link><p className="mt-1 text-xs text-zinc-500">{user.email}</p></td><td className="p-3">{user.goal ?? "—"}</td><td className="p-3">{user.dailyCalorieTarget ?? "—"}</td><td className="p-3">{new Intl.DateTimeFormat("fa-IR", { dateStyle: "medium" }).format(new Date(user.createdAt))}</td><td className="p-3"><span className={`rounded px-2 py-1 text-xs ${user.suspended ? "bg-red-100 text-red-700" : "bg-emerald-100 text-emerald-700"}`}>{user.suspended ? "معلق" : "فعال"}</span></td></tr>)}</tbody></table></div></section>; }
